services:
  app:
    image: bellsoft/liberica-openjdk-debian:25
    container_name: flux
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    workin_dir: /srv
    depends_on:
      - db

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
